### PR TITLE
Simplify the unsafe callback code in path finding

### PR DESCRIPTION
**Pull request by tomassedovic**
We don't have to cast the callback closure to a trait object and
therefore store its fat pointer and pass that as libtcod's user data. By
making `c_path_callback` generic over the closure, we can pass the
pointer to the closure as user data directly.

This saves us an extra indirection, makes the code simpler and gets rid
of `mem::transmute`.

I've tested this on the examples and ran them through valgrind. Astar is
clean as before, Dijkstra is showing memory issues, but again, that's
same as before.

### CODE REVIEW

**Comment by Gustorn** [comment]
The memory leak in the Dijkstra pathfinding is acutally an upstream bug, the following patch fixes it:

```patch
From f723660edc6da6834e3b50844ae650043d01a8bc Mon Sep 17 00:00:00 2001
From: Gustorn <gustorn@gmail.com>
Date: Wed, 19 Aug 2015 01:24:34 +0200
Subject: [PATCH] Memory leak fix

---
 tcod_sys/libtcod/src/path_c.c | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/tcod_sys/libtcod/src/path_c.c b/tcod_sys/libtcod/src/path_c.c
index 038c2a8..7637b9b 100644
--- a/tcod_sys/libtcod/src/path_c.c
+++ b/tcod_sys/libtcod/src/path_c.c
@@ -658,7 +658,10 @@ void TCOD_dijkstra_delete (TCOD_dijkstra_t dijkstra) {
 	TCOD_IFNOT(data != NULL) return;
 	if ( data->distances ) free(data->distances);
 	if ( data->nodes ) free(data->nodes);
-	if ( data->path ) TCOD_list_clear(data->path);
+	if ( data->path ) {
+        TCOD_list_clear_and_delete(data->path);
+        TCOD_list_delete(data->path);
+    }
 	free(data);
 }
 
-- 
2.5.0
```

**Comment by tomassedovic** [comment]
Thanks! I knew this was an upstream issue but didn't track it down yet. So this fixes the memory leaks but not the other errors Valgrind reports, right?

I'm still seeing a bunch of "Use of uninitialised value of size 8" and "Conditional jump or move depends on uninitialised value(s)" issues, but no more memory leaks.

I'll merge this to our libtcod copy in tcod_sys if you don't mind.

**Comment by Gustorn** [comment]
Wow, I totally missed the conditional jumps and unitialized values... I'll see if I can track those down too.

**Comment by Gustorn** [comment]
Here's the patch for the uninitialized values and conditional jumps (they were basicly the same problem):

```patch
From 2e8db4bfc6803b6386b3a6ab93626602a706917c Mon Sep 17 00:00:00 2001
From: Gustorn <gustorn@gmail.com>
Date: Wed, 19 Aug 2015 15:54:17 +0200
Subject: [PATCH] Uninitialized access fix

---
 tcod_sys/libtcod/src/path_c.c | 15 ++++++++++-----
 1 file changed, 10 insertions(+), 5 deletions(-)

diff --git a/tcod_sys/libtcod/src/path_c.c b/tcod_sys/libtcod/src/path_c.c
index 7637b9b..2ee6d1f 100644
--- a/tcod_sys/libtcod/src/path_c.c
+++ b/tcod_sys/libtcod/src/path_c.c
@@ -521,12 +521,17 @@ void TCOD_dijkstra_compute (TCOD_dijkstra_t dijkstra, int root_x, int root_y) {
 	unsigned int * distances = data->distances;
 	TCOD_IFNOT(data != NULL) return;
 	TCOD_IFNOT((unsigned)root_x < (unsigned)mx && (unsigned)root_y < (unsigned)my) return;
-	memset(distances,0xFFFFFFFF,mmax*sizeof(int));
+	memset(distances, 0xFFFFFFFF, mmax*sizeof(int));
+	memset(nodes, 0xFFFFFFFF, mmax * sizeof(int));
 	/* data for root node is known... */
 	distances[root] = 0;
 	nodes[index] = root; /*set starting note to root */
 	/* and the loop */
 	do {
+		if (nodes[index] == 0xFFFFFFFF) {
+			continue;
+		}
+
 		/* coordinates of currently processed node */
 		unsigned int x = nodes[index] % mx;
 		unsigned int y = nodes[index] / mx;
@@ -550,7 +555,7 @@ void TCOD_dijkstra_compute (TCOD_dijkstra_t dijkstra, int root_x, int root_y) {
 				/* ..., encode coordinates, ... */
 				new_node = (ty * mx) + tx;
 				/* and check if the node's eligible for queuing */
-				 if (distances[new_node] > dt) {
+				if (distances[new_node] > dt) {
 					unsigned int j;
 					/* if not walkable, don't process it */
 					if (data->map && !TCOD_map_is_walkable(data->map,tx,ty)) continue;
@@ -659,9 +664,9 @@ void TCOD_dijkstra_delete (TCOD_dijkstra_t dijkstra) {
 	if ( data->distances ) free(data->distances);
 	if ( data->nodes ) free(data->nodes);
 	if ( data->path ) {
-        TCOD_list_clear_and_delete(data->path);
-        TCOD_list_delete(data->path);
-    }
+		TCOD_list_clear_and_delete(data->path);
+		TCOD_list_delete(data->path);
+	}
 	free(data);
 }
 
-- 
2.5.0
```

As a sidenote, I'm amazed that the version `libtcod` has actually worked (at all). That was dependent on a lot of random chance... Also the `libtcod` codebase is a mess.

**Comment by Gustorn** [comment]
I'll actually create a branch based on this safer pathfinding one and fix some `libtcod` problems. Still, feel free to merge the previous patch if you want to.

**Comment by tomassedovic** [comment]
Ooh, cool. Okay, I've merged the memory leak patch and feel free add this as a separate PR.

**Comment by Gustorn** [comment]
I sent the PR, it fixes things on my end.

**Pull request merged**
