### PR TITLE
Fixed uninitialized error in `check_for_events`

### PR DESCRIPTION
**Pull request by ojhp**
Replaced uninitialised calls with MaybeUninit.

### CODE REVIEW

**Comment by tomassedovic** [comment]
Thanks! Running `cargo run --example samples` (and others) no longer panics.

@ojhp this project has a policy of giving merge access to people who get code accepted. Would you be interested in that?

(note that none of the current maintainers including myself are able to devote time and effort to future development of tcod-rs, but I'll keep merging PRs when I get to it)

**Comment by ojhp** [comment]
@tomassedovic Sure, I'm happy to help out when I get a chance. Just let me know if there's any contributors rules or anything.

**Comment by tomassedovic** [comment]
@ojhp the rules are just: open a PR instead of pushing directly, give others some time (1-2 days) before merging your own change, don't do anything malicious and don't be an arsehole.

I've sent you an invite.

**Comment by ojhp** [comment]
Nice and simple, thanks!

**Pull request merged**
