### PR TITLE
Rng not consumed in split_recursive

### PR DESCRIPTION
**Pull request by L3nn0x**

### CODE REVIEW

**Comment by L3nn0x** [comment]
Any update on this? This is in response to #260

**Comment by L3nn0x** [comment]
@tomassedovic @Gustorn @lucanLepus Would it be possible to have a review?

Thanks!

**Comment by tomassedovic** [comment]
Hey @L3nn0x I'm so sorry it took so long for me to get to this.

It looks good to me and haven't had any crashes when I played with the BSP bit in examples/samples.rs, so I'm going to merge this.

I'd also like to thank you for handling the issues and PRs in my absence! Cheers!

**Comment by L3nn0x** [comment]
Sure no worries! I don't have much time to push changes but I try to find some to answer issues and PRs!

**Pull request merged**
