### PR TITLE
Remove unnecessary casts

### PR DESCRIPTION
**Pull request by tomassedovic**
This silences the new warnings introduced in the latest nightly.

### CODE REVIEW

**Comment by tomassedovic** [comment]
Hm, Travis, crates.io or cargo is having some issues...

**Comment by jgilchrist** [comment]
I re-triggered the build on Travis, seems the failure isn't related to the PR so hopefully it should pass this time.

**Comment by jgilchrist** [comment]
Yep, it's passing, just an intermittent failure.

**Comment by tomassedovic** [comment]
Thanks! I've seen the same failure on master (but not locally), wanted to wait before the dust settles a bit.

**Pull request merged**
