### PR TITLE
Update to work with current nightly

### PR DESCRIPTION
**Pull request by GGalizzi**
Change `box x` to `Box::new(x)`

As well as changing deprecated int/uint to isize/usize as well as `u` suffix to `us`

### CODE REVIEW

**Comment by GGalizzi** [comment]
Oh, the examples are gonna need fixing :\

**Comment by tomassedovic** [comment]
Thanks! I've a bit of time on my hands now. I'll add the examples on top of this pull request, if you don't mind (since I can't push to your fork, that'll probably involve another PR with both of our commits).

**Comment by GGalizzi** [comment]
Alright, yeah, that'd be fine of course :)

**Comment by tomassedovic** [comment]
okay, closing this in favour of: https://github.com/tomassedovic/tcod-rs/pull/72

(it has the two commits here unchanged + a new one fixing the examples)

**Pull request closed without merging**
