### PR TITLE
Update for latest Rust

### PR DESCRIPTION
**Pull request by indiv0**

### CODE REVIEW

**Comment by tomassedovic** [comment]
Thanks @indiv0! I updated to latest Rust this morning and it was all right. Sigh :-)

Do you fancy commit access to `tcod-rs`? Everyone who makes a contribution is eligible.

**Comment by indiv0** [comment]
@tomassedovic sure! :)

**Comment by tomassedovic** [comment]
Awesome, you should be set up now :-)

**Comment by indiv0** [comment]
@tomassedovic yeah I'll stick with PRs.

We do something similar with Piston, where everything is a PR and we like to have at least one other set of eyes confirm the change. A CI run is always nice too :)

**Comment by tomassedovic** [comment]
Yep :-)

**Pull request merged**
