### PR TITLE
Removed email for contributor Nikita Pekin

### PR DESCRIPTION
**Pull request by indiv0**

### CODE REVIEW

**Comment by tomassedovic** [comment]
Sorry! There's one in Cargo.toml as well. I assume you want to remove that as well. I can push it quickly if you want.

**Comment by indiv0** [comment]
@tomassedovic ah I missed that. Yes please that would be great!

**Comment by tomassedovic** [comment]
@indiv0 done. Sorry again for putting it there in the first place.

**Comment by indiv0** [comment]
@tomassedovic thank you very much! And don't be sorry, I didn't really have a problem with it. It's just that I've been getting more spam recently so I'm trying to limit the number of places it appears.

**Pull request merged**
